service: esp-ws-api-gateway

package:
  individually: true

custom:
  variables: ${file(serverless/variables.yml)}
  prune:
    automatic: true
    number: 1

plugins:
  - serverless-pseudo-parameters
  - serverless-offline
  - serverless-prune-plugin

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'local'}
  region: ${opt:region, 'us-east-1'}
  environment: ${file(serverless/env.yml):${self:provider.stage}}
  apiGateway:
    minimumCompressionSize: 1024
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:Query
      Resource:
        - { 'Fn::GetAtt': ['DynamoDBTableProcessCreationStatus', 'Arn'] }
    - Effect: Allow
      Action:
        - sqs:SendMessage
        - sqs:DeleteMessage
      Resource:
        - ${self:custom.variables.create-process-sqs-queue-arn}
    - Effect: Allow
      Action:
        - kms:Decrypt
        - kms:GenerateDataKey
      Resource: '*'

functions:
  - ${file(serverless/functions/connect.yml)}
  - ${file(serverless/functions/create-process.yml)}
  - ${file(serverless/functions/disconnect.yml)}
  - ${file(serverless/functions/notify-stream.yml)}
  - ${file(serverless/functions/start-process.yml)}

resources:
  - ${file(serverless/resources/aws-dynamo-process-creation-status-table.yml)}
  - ${file(serverless/resources/aws-sqs-create-process-queue.yml)}