service: backend

package:
  individually: true

plugins:
  - serverless-pseudo-parameters
  - serverless-offline
  - serverless-prune-plugin

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  apiGateway:
    minimumCompressionSize: 1024
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:Query
      Resource:
        - { 'Fn::GetAtt': ['DynamoDBTableProcessCreationStatus', 'Arn'] }
    - Effect: Allow
      Action:
        - sqs:SendMessage
        - sqs:DeleteMessage
      Resource:
        - ${self:custom.variables.create-process-sqs-queue-arn}
    - Effect: Allow
      Action:
        - kms:Decrypt
        - kms:GenerateDataKey
      Resource: '*'

functions:
  connect:
    handler: connectWS.main
    events:
      - websocket:
          route: $connect

  disconnect:
    handler: disconnectWS.main
    events:
      - websocket:
          route: $disconnect

functions:
  - ${file(serverless/functions/connect.yml)}
  - ${file(serverless/functions/create-process.yml)}
  - ${file(serverless/functions/disconnect.yml)}
  - ${file(serverless/functions/notify-stream.yml)}
  - ${file(serverless/functions/start-issuance.yml)}

resources:
  - ${file(serverless/resources/aws-dynamodb-user-connection-status-table.yml)}
  - ${file(serverless/resources/aws-sqs-create-process-queue)}